"""
Django settings for filerp project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path
import yaml

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*&u+o$=d5h9_%)stfm=liqu_4w)$j*kiho5yv@c@q37)cu-g*f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Standard localhost, Android localhost
ALLOWED_HOSTS = ["10.0.2.2", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'data_center',
    'payment_solutions',
    'report_center',
    'eccommerce_solutions'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'filerp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'filerp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "../public/static")

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "../public/media")

ORGANISATION_LOGO = './public/images/logos/logo_img.png'
PDF_FILES_DIRECTORY = os.path.join(BASE_DIR, 'public/pdf')

INVOICES_DIRECTORY = os.path.join(PDF_FILES_DIRECTORY, 'invoices')
QUOTATIONS_DIRECTORY = os.path.join(PDF_FILES_DIRECTORY, 'quotations')

EXCEL_IN_FILE_SOURCE = os.path.join(BASE_DIR, 'excel_files/in_files_source')
EXCEL_OUT_FILE_SOURCE = os.path.join(BASE_DIR, 'excel_files/out_files_source')


# YAML CONFIG
CONFIG_ROOT = os.path.join(BASE_DIR, "config.yaml")
file = open(CONFIG_ROOT)
app_config = yaml.load(file, Loader=yaml.FullLoader)
INVOICE_ITEMS_PER_PAGE = app_config.get('invoices_items_per_page')
QUOTATION_ITEMS_PER_PAGE = app_config.get('quotation_items_per_page')
BANK_DETAILS = app_config.get('bank_details')

SHOP_HOST_URL = app_config.get('shop_host_url')
WOO_COMM_CONSUMER_KEY = app_config.get('woo_commerce_cbank_detailsonsumer_key')
WOO_COMM_CONSUMER_SECRET = app_config.get('woo_commerce_consumer_secret')

TMDB_API_KEY = app_config.get('tmdb_api_key')
TMDB_API_ACCESS_TOKEN = app_config.get('tmdb_access_token')

NEWS_API_KEY = app_config.get('news_api_key')

EMAIL_SMTP_SERVER = app_config.get('email_smtp_server')
SENDER_EMAIL = app_config.get('sender_email')
SENDER_EMAIL_PASSWORD = app_config.get('sender_email_password')
BCC_EMAIL_RECIPIENTS = app_config.get('bcc_sender_email')
EMAIL_RETRIES_COUNT = app_config.get('email_retries_count')

SSH_SERVER_ADDRESS = app_config.get('server_ip_address')
